name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake
